<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <RootNamespace>NMolecules.Bricks</RootNamespace>
    <Version>0.2.2</Version>
    <PackageId>NMolecules.Bricks.Extensions</PackageId>
    <PackageDescription>Extended reporting, governance, runtime, visibility and operational types for nMolecules Bricks.</PackageDescription>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <PackageIcon>caffeine-molecule.png</PackageIcon>
    <Title>nMolecules Bricks Extensions</Title>
    <Authors>Oliver Drotbohm, Stephan Pirnbaum, Henning Schwentner</Authors>
    <PackageLicenseExpression>Apache-2.0</PackageLicenseExpression>
    <RepositoryUrl>https://github.com/xmolecules/nmolecules</RepositoryUrl>
    <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="System.Text.Json" Version="8.0.5" />
    <ProjectReference Include="..\nMolecules.Bricks\nMolecules.Bricks.csproj" />
    <None Include="..\..\images\caffeine-molecule.png" Pack="true" PackagePath="" />
    <None Include="README.md" Pack="true" PackagePath="" />
  </ItemGroup>
</Project>
