

namespace NMolecules.Bricks
{
/// <summary>
    /// Describes where an architecture element originally came from. Use it to
    /// distinguish source-code facts from generated, external, or metadata-only facts.
    /// </summary>
    public enum BrickElementOrigin
    {
        /// <summary>The origin is unknown.</summary>
        Unknown = 0,
        /// <summary>The element was declared in analyzed source code.</summary>
        Source = 1,
        /// <summary>The element was generated by a tool or source generator.</summary>
        Generated = 2,
        /// <summary>The element belongs to an external dependency or external system.</summary>
        External = 3,
        /// <summary>The element was discovered from metadata rather than source code.</summary>
        Metadata = 4
    }
}
