namespace NMolecules.Bricks
{
    /// <summary>
    /// Describes which kind of architecture element a Bricks fact refers to.
    /// Use it when selecting, reporting, or evaluating dependencies at assembly,
    /// namespace, type, member, or infrastructure-registration level.
    /// </summary>
    public enum BrickElementKind
    {
        /// <summary>The element kind is not known or could not be mapped.</summary>
        Unknown = 0,
        /// <summary>A .NET assembly or comparable package boundary.</summary>
        Assembly = 1,
        /// <summary>A namespace or logical namespace-like grouping.</summary>
        Namespace = 2,
        /// <summary>A type such as a class, interface, struct, record, or enum.</summary>
        Type = 3,
        /// <summary>A member such as a method, constructor, property, field, or event.</summary>
        Member = 4,
        /// <summary>An attribute type or attribute usage that participates in role or rule metadata.</summary>
        Attribute = 5,
        /// <summary>A dependency-injection, composition-root, or service-registration element.</summary>
        DependencyRegistration = 6,
        /// <summary>An external package, service, framework type, or system outside the analyzed codebase.</summary>
        ExternalReference = 7
    }

    /// <summary>
    /// Describes where an architecture element originally came from. Use it to
    /// distinguish source-code facts from generated, external, or metadata-only facts.
    /// </summary>
    public enum BrickElementOrigin
    {
        /// <summary>The origin is unknown.</summary>
        Unknown = 0,
        /// <summary>The element was declared in analyzed source code.</summary>
        Source = 1,
        /// <summary>The element was generated by a tool or source generator.</summary>
        Generated = 2,
        /// <summary>The element belongs to an external dependency or external system.</summary>
        External = 3,
        /// <summary>The element was discovered from metadata rather than source code.</summary>
        Metadata = 4
    }

    /// <summary>
    /// Describes which input channel contributed an element or assignment.
    /// Use it when explaining why a role, element, or policy fact exists.
    /// </summary>
    public enum BrickElementSource
    {
        /// <summary>The source channel is unknown.</summary>
        Unknown = 0,
        /// <summary>The fact came directly from code.</summary>
        Code = 1,
        /// <summary>The fact came from configuration such as policy files or build settings.</summary>
        Configuration = 2,
        /// <summary>The fact came from a naming or structural convention.</summary>
        Convention = 3,
        /// <summary>The fact was inferred by an analyzer or heuristic.</summary>
        Inference = 4,
        /// <summary>The fact came from an imported package, profile, or role pack.</summary>
        Import = 5
    }

    /// <summary>
    /// Defines the architectural level at which a rule, dependency, or violation
    /// is evaluated. Use it to make clear whether a check applies to a type,
    /// member, namespace, assembly, or the whole model.
    /// </summary>
    public enum BrickScope
    {
        /// <summary>The check applies at type level.</summary>
        Type = 0,
        /// <summary>The check applies at member level.</summary>
        Member = 1,
        /// <summary>The check applies at namespace level.</summary>
        Namespace = 2,
        /// <summary>The check applies at assembly level.</summary>
        Assembly = 3,
        /// <summary>The check applies globally to the complete analyzed model.</summary>
        Global = 4
    }

    /// <summary>
    /// Describes the observation layer where a dependency was found. Use it to
    /// separate compile-time references from visibility, runtime, and configuration links.
    /// </summary>
    public enum BrickDependencyLayer
    {
        /// <summary>A static code dependency such as a type reference, inheritance, or member usage.</summary>
        Static = 0,
        /// <summary>A visibility dependency such as friend assemblies or internal exposure.</summary>
        Visibility = 1,
        /// <summary>A runtime dependency such as activation, reflection, plugin loading, or service resolution.</summary>
        Runtime = 2,
        /// <summary>A configuration dependency such as DI registration, config binding, or policy wiring.</summary>
        Configuration = 3
    }

    /// <summary>
    /// Describes how strongly a dependency is connected to the source element.
    /// Use it to communicate whether evidence is direct, indirect, or inferred.
    /// </summary>
    public enum BrickDependencyStrength
    {
        /// <summary>The source directly references or uses the target.</summary>
        Direct = 0,
        /// <summary>The dependency exists through an intermediate element or indirection.</summary>
        Indirect = 1,
        /// <summary>The dependency was inferred and may need supporting evidence.</summary>
        Inferred = 2
    }

    /// <summary>
    /// Describes how reliable the evidence behind a dependency or violation is.
    /// Use it to rank findings and decide whether human review is required.
    /// </summary>
    public enum BrickEvidenceLevel
    {
        /// <summary>The compiler or semantic model confirms the evidence.</summary>
        CompilerConfirmed = 0,
        /// <summary>An analyzer inferred the evidence from code structure.</summary>
        AnalyzerInferred = 1,
        /// <summary>Configuration explicitly declared the evidence.</summary>
        ConfigurationDeclared = 2,
        /// <summary>Runtime observation or runtime metadata inferred the evidence.</summary>
        RuntimeInferred = 3,
        /// <summary>The evidence level is unknown.</summary>
        Unknown = 4
    }

    /// <summary>
    /// Describes confidence in reflection-based observations. Use it when a
    /// dependency can be seen only through reflection or dynamic access patterns.
    /// </summary>
    public enum BrickReflectionConfidence
    {
        /// <summary>The reflection evidence is weak and should usually be reviewed.</summary>
        Low = 0,
        /// <summary>The reflection evidence is plausible but not as strong as compiler evidence.</summary>
        Medium = 1,
        /// <summary>The reflection evidence is strong enough for regular reporting.</summary>
        High = 2
    }

    /// <summary>
    /// Describes the policy decision a rule makes for matching dependencies.
    /// Use it to model allowed, forbidden, and required architecture relations.
    /// </summary>
    public enum BrickDecision
    {
        /// <summary>The matching dependency is allowed.</summary>
        Allow = 0,
        /// <summary>The matching dependency is forbidden.</summary>
        Deny = 1,
        /// <summary>The matching dependency is required and missing evidence may become a violation.</summary>
        Require = 2
    }

    /// <summary>
    /// Defines the default behavior for dependencies not matched by any explicit
    /// rule. Use it to choose between permissive and allow-list style policies.
    /// </summary>
    public enum BrickPermissionDefault
    {
        /// <summary>Unmatched dependencies are allowed.</summary>
        Allow = 0,
        /// <summary>Unmatched dependencies are denied unless an explicit rule allows them.</summary>
        Deny = 1
    }

    /// <summary>
    /// Defines how strongly a policy participates in tooling. Use it to move
    /// from documentation through analysis to build-breaking enforcement.
    /// </summary>
    public enum BrickEnforcementMode
    {
        /// <summary>The policy is present but not active.</summary>
        Disabled = 0,
        /// <summary>The policy is documented but does not produce active analyzer findings.</summary>
        Document = 1,
        /// <summary>The policy produces analysis results without necessarily breaking builds.</summary>
        Analyze = 2,
        /// <summary>The policy is enforced and errors may fail builds or quality gates.</summary>
        Enforce = 3
    }

    /// <summary>
    /// Describes the severity of a finding. Use it to map Bricks findings to
    /// diagnostics, reports, CI gates, and review workflows.
    /// </summary>
    public enum BrickSeverity
    {
        /// <summary>Informational finding that does not require immediate action.</summary>
        Info = 0,
        /// <summary>Warning that should be reviewed or fixed according to team policy.</summary>
        Warning = 1,
        /// <summary>Error that represents a broken rule or build-blocking issue.</summary>
        Error = 2
    }

    /// <summary>
    /// Describes why a violation exists. Use it to separate dependency-rule
    /// problems from role-resolution, configuration, baseline, suppression, and member-contract issues.
    /// </summary>
    public enum BrickViolationKind
    {
        /// <summary>A dependency matched a forbidden or denied dependency rule.</summary>
        DependencyRule = 0,
        /// <summary>A required dependency was missing.</summary>
        RequiredDependency = 1,
        /// <summary>Role assignment or role resolution produced an issue.</summary>
        RoleResolution = 2,
        /// <summary>A role-combination rule was violated.</summary>
        RoleCombination = 3,
        /// <summary>The policy itself is invalid, incomplete, or unsupported.</summary>
        PolicyConfiguration = 4,
        /// <summary>The finding relates to a baseline entry.</summary>
        Baseline = 5,
        /// <summary>The finding relates to a suppression entry.</summary>
        Suppression = 6,
        /// <summary>A member-cardinality contract was violated.</summary>
        MemberCardinality = 7
    }

    /// <summary>
    /// Describes the lifecycle state of a violation. Use it to distinguish
    /// active violations from reviewed exceptions and expired exceptions.
    /// </summary>
    public enum BrickViolationState
    {
        /// <summary>The violation is active and still needs action or acceptance.</summary>
        Active = 0,
        /// <summary>The violation is intentionally suppressed by a reviewed suppression.</summary>
        Suppressed = 1,
        /// <summary>The violation is accepted as part of a baseline.</summary>
        Baselined = 2,
        /// <summary>The suppression exists but is past its expiry.</summary>
        ExpiredSuppression = 3,
        /// <summary>The baseline entry exists but is past its expiry.</summary>
        ExpiredBaseline = 4
    }

    /// <summary>
    /// Describes how imported policies are merged into a root policy. Use it
    /// when composing platform defaults, package policies, and project-specific policies.
    /// </summary>
    public enum BrickPolicyImportMode
    {
        /// <summary>Import the referenced policy as-is.</summary>
        Import = 0,
        /// <summary>Add the referenced policy to the root policy.</summary>
        Extend = 1,
        /// <summary>Let the importing policy replace overlapping imported decisions.</summary>
        Override = 2,
        /// <summary>Disable the referenced imported policy.</summary>
        Disable = 3,
        /// <summary>Keep only stricter or narrower imported behavior.</summary>
        Narrow = 4
    }

    /// <summary>
    /// Describes how specific a role assignment is. Use it as one part of
    /// precedence when multiple role assignments compete.
    /// </summary>
    public enum BrickAssignmentSpecificity
    {
        /// <summary>The assignment came from broad inference.</summary>
        Inference = 0,
        /// <summary>The assignment came from a convention.</summary>
        Convention = 1,
        /// <summary>The assignment applies at assembly level.</summary>
        Assembly = 2,
        /// <summary>The assignment applies at namespace level.</summary>
        Namespace = 3,
        /// <summary>The assignment applies directly to the element.</summary>
        Element = 4
    }

    /// <summary>
    /// Describes the authority of a role assignment. Use it as one part of
    /// precedence when resolving aliases, external policy, generated facts, and direct annotations.
    /// </summary>
    public enum BrickAssignmentAuthority
    {
        /// <summary>The assignment was derived and has the lowest authority.</summary>
        Derived = 0,
        /// <summary>The assignment came through an alias mapping.</summary>
        Alias = 1,
        /// <summary>The assignment came from external configuration or a policy document.</summary>
        External = 2,
        /// <summary>The assignment came directly from source metadata or explicit declaration.</summary>
        Direct = 3
    }

    /// <summary>
    /// Describes how a role assignment was created. Use it when auditing role
    /// resolution or explaining why a type received a role.
    /// </summary>
    public enum BrickAssignmentMode
    {
        /// <summary>The role came from a direct role attribute on the element.</summary>
        DirectAttribute = 0,
        /// <summary>The role came from external configuration.</summary>
        ExternalConfiguration = 1,
        /// <summary>The role came from a convention.</summary>
        Convention = 2,
        /// <summary>The role was inferred by analysis.</summary>
        Inference = 3,
        /// <summary>The role came from an alias mapping.</summary>
        AliasMapping = 4,
        /// <summary>The role came from an imported role pack or package policy.</summary>
        ImportedPack = 5,
        /// <summary>The role was generated by tooling.</summary>
        Generated = 6
    }

    /// <summary>
    /// Describes where a role assignment was sourced from. Use it for provenance
    /// in reports, resolution traces, and conflict explanations.
    /// </summary>
    public enum BrickAssignmentSource
    {
        /// <summary>The role came from a source-code attribute.</summary>
        SourceAttribute = 0,
        /// <summary>The role came from a policy file.</summary>
        PolicyFile = 1,
        /// <summary>The role came from a convention.</summary>
        Convention = 2,
        /// <summary>The role came from inference.</summary>
        Inference = 3,
        /// <summary>The role came from alias mapping.</summary>
        AliasMapping = 4,
        /// <summary>The role came from a package.</summary>
        Package = 5,
        /// <summary>The role came from a generator.</summary>
        Generator = 6
    }

    /// <summary>
    /// Describes whether an assignment contributes a role or intentionally hides
    /// one. Use it for role overrides, suppressions, and migration scenarios.
    /// </summary>
    public enum BrickAssignmentBehavior
    {
        /// <summary>Apply the assignment.</summary>
        Apply = 0,
        /// <summary>Suppress or remove the matching assignment.</summary>
        Suppress = 1
    }

    /// <summary>
    /// Describes how two roles may be combined on one element. Use it to express
    /// whether roles can coexist, compete, or must never be combined.
    /// </summary>
    public enum BrickCombinationKind
    {
        /// <summary>The roles may be combined and reinforce each other.</summary>
        Additive = 0,
        /// <summary>Only one of the roles should win after precedence resolution.</summary>
        Exclusive = 1,
        /// <summary>The roles must not be combined on the same element.</summary>
        Incompatible = 2
    }

    /// <summary>
    /// Describes the configuration channel that supplied Bricks settings. Use it
    /// to explain configuration precedence across generated defaults, packages,
    /// policy files, MSBuild, analyzer config, and source annotations.
    /// </summary>
    public enum BrickConfigurationSourceKind
    {
        /// <summary>Generated defaults supplied the configuration.</summary>
        Generated = 0,
        /// <summary>A package supplied the configuration.</summary>
        Package = 1,
        /// <summary>A policy file supplied the configuration.</summary>
        PolicyFile = 2,
        /// <summary>MSBuild properties or items supplied the configuration.</summary>
        MSBuild = 3,
        /// <summary>.editorconfig or analyzer-config options supplied the configuration.</summary>
        AnalyzerConfig = 4,
        /// <summary>Source-code annotations supplied the configuration.</summary>
        SourceAnnotation = 5
    }
}
