

namespace NMolecules.Bricks
{
/// <summary>
    /// Describes how a role assignment was created. Use it when auditing role
    /// resolution or explaining why a type received a role.
    /// </summary>
    public enum BrickAssignmentMode
    {
        /// <summary>The role came from a direct role attribute on the element.</summary>
        DirectAttribute = 0,
        /// <summary>The role came from external configuration.</summary>
        ExternalConfiguration = 1,
        /// <summary>The role came from a convention.</summary>
        Convention = 2,
        /// <summary>The role was inferred by analysis.</summary>
        Inference = 3,
        /// <summary>The role came from an alias mapping.</summary>
        AliasMapping = 4,
        /// <summary>The role came from an imported role pack or package policy.</summary>
        ImportedPack = 5,
        /// <summary>The role was generated by tooling.</summary>
        Generated = 6
    }
}
